# Generated by Django 3.0.7 on 2020-06-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Application')),
            ],
        ),
    ]
