# Generated by Django 3.0.7 on 2020-06-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_auto_20200606_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
    ]
