# Generated by Django 3.0.7 on 2020-06-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_auto_20200606_1802'),
        ('Interview', '0002_auto_20200606_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Session.Session'),
        ),
    ]
